apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bgpglobals.eos.netclab.dev
spec:
  compositeTypeRef:
    apiVersion: eos.netclab.dev/v1alpha1
    kind: BgpGlobal
  mode: Pipeline
  pipeline:
  - step: environmentConfigs
    functionRef:
      name: crossplane-contrib-function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
        - type: Reference
          ref:
            name: endpoint-protocols

  - step: requests
    functionRef:
      name: crossplane-contrib-function-go-templating

    credentials:
    - name: eos-creds
      secretRef:
        name: eos-creds
        namespace: crossplane-system
      source: Secret

    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{ $resourceNamePrefix := .observed.composite.resource.metadata.name }}

          {{- $deviceUrl := "" }}
          {{- $basicAuth := "" }}
          {{- $address := .observed.composite.resource.spec.endpoint }}
          {{- with index .context "apiextensions.crossplane.io/environment" }}
            {{- $deviceUrl = printf "%s://%s:%d" .restconf.scheme $address .restconf.port }}
          {{- end }}
          {{- $basicAuth := ( getCredentialData . "eos-creds" ).basicAuth | toString | b64enc }}

          {{ $asn := .observed.composite.resource.spec.asn }}
          {{ $routerId := .observed.composite.resource.spec.routerId }}

          ---
          apiVersion: http.crossplane.io/v1alpha2
          kind: Request
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $resourceNamePrefix }}-asid
          spec:
            forProvider:
              insecureSkipTLSVerify: true
              headers:
                Accept: ["application/yang-data+json"]
                Authorization: ["Basic {{ $basicAuth }}"]
              payload:
                baseUrl: "{{ $deviceUrl }}/restconf/data/openconfig-network-instance:network-instances/network-instance=default/protocols/protocol=BGP,BGP/bgp/global/config"
                body: |
                  { "openconfig-network-instance:as": {{ $asn }}, "openconfig-network-instance:router-id": "{{ $routerId }}" }

              mappings:
              - action: CREATE
                method: PATCH
                body: .payload.body
                url: .payload.baseUrl

              - action: UPDATE
                method: PATCH
                body: .payload.body
                url: .payload.baseUrl

              - action: OBSERVE
                url: .payload.baseUrl

              - action: REMOVE
                method: DELETE
                url: .payload.baseUrl

          {{- if and (hasKey .observed.composite.resource.spec "disableBgpDefaultIpv4Unicast") .observed.composite.resource.spec.disableBgpDefaultIpv4Unicast }}
          ---
          apiVersion: http.crossplane.io/v1alpha2
          kind: Request
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $resourceNamePrefix }}-disableIp4
          spec:
            forProvider:
              insecureSkipTLSVerify: true
              headers:
                Accept: ["application/yang-data+json"]
                Authorization: ["Basic {{ $basicAuth }}"]
              payload:
                baseUrl: "{{ $deviceUrl }}/restconf/data/openconfig-network-instance:network-instances/network-instance=default/protocols/protocol=BGP,BGP/bgp/global/afi-safis/afi-safi=IPV4_UNICAST/config"
                body: |
                  {"openconfig-network-instance:enabled": false}

              mappings:
              - action: CREATE
                method: PATCH
                url: .payload.baseUrl
                body: .payload.body

              - action: UPDATE
                method: PATCH
                url: .payload.baseUrl
                body: .payload.body

              - action: OBSERVE
                url: .payload.baseUrl

              - action: REMOVE
                method: DELETE
                url: .payload.baseUrl
          {{- end }}

          {{- if hasKey .observed.composite.resource.spec "maximumPaths" }}
          ---
          apiVersion: eos.netclab.dev/v1alpha1
          kind: BgpMultiPath
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $resourceNamePrefix }}-mpath
          spec:
            endpoint: {{ $address }}
            asn: {{ $asn }}
            maximumPaths:
              number: {{ .observed.composite.resource.spec.maximumPaths.number }}
              ecmp: {{ .observed.composite.resource.spec.maximumPaths.ecmp }}
          {{- end }}

  - step: auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
