apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: vlaninternalallocations.eos.netclab.dev
spec:
  defaultCompositionRef:
    name: vlaninternalallocations.eos.netclab.dev
  scope: Cluster
  group: eos.netclab.dev
  names:
    kind: VlanInternalAllocation
    plural: vlaninternalallocations
    categories:
    - crossplane
    - netclab
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - name: ENDPOINT
      type: string
      jsonPath: .spec.endpoint
    - name: ORDER
      type: string
      jsonPath: .spec.order
    - name: START
      type: integer
      jsonPath: .spec.range.start
    - name: END
      type: integer
      jsonPath: .spec.range.end
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              endpoint:
                type: string
              order:
                type: string
                enum:
                - ascending
                - descending
              range:
                type: object
                properties:
                  start:
                    type: integer
                  end:
                    type: integer
                required:
                - start
                - end
            required:
            - endpoint
            - order
            - range
