apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vlaninternalallocations.eos.netclab.dev
spec:
  compositeTypeRef:
    apiVersion: eos.netclab.dev/v1alpha1
    kind: VlanInternalAllocation
  mode: Pipeline
  pipeline:
  - step: set-vlaninternalallocation
    functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          apiVersion: http.crossplane.io/v1alpha2
          kind: Request
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.metadata.name }}-internalvlanallocation
          spec:
            forProvider:
              insecureSkipTLSVerify: true
              headers:
                Accept: ["application/json"]
                Authorization: ["Basic {{ .observed.composite.resource.spec.creds }}"]
              payload:
                baseUrl: "{{ .observed.composite.resource.spec.target }}/command-api"
                body: |
                  {
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "runCmds",
                    "params": {
                      "version": 1,
                      "format": "json",
                      "cmds": [
                        "enable",
                        "configure",
                        "vlan internal order {{ .observed.composite.resource.spec.order }} range {{ .observed.composite.resource.spec.range.start }} {{ .observed.composite.resource.spec.range.end }}"
                      ]
                    }
                  }

              mappings:
              - action: CREATE
                method: POST
                body: .payload.body
                url: .payload.baseUrl

              - action: UPDATE
                method: POST
                body: .payload.body
                url: .payload.baseUrl

              - action: OBSERVE
                method: POST
                url: .payload.baseUrl
                body: |
                  {
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "runCmds",
                    "params": {
                      "version": 1,
                      "format": "json",
                      "cmds": [
                        "enable",
                         "show vlan internal allocation policy"
                      ]
                    }
                  }

              - action: REMOVE
                method: POST
                url: .payload.baseUrl
                body: |
                  {
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": "runCmds",
                    "params": {
                      "version": 1,
                      "format": "json",
                      "cmds": [
                        "enable",
                        "configure",
                        "no vlan internal order"
                      ]
                    }
                  }

              expectedResponseCheck:
                type: CUSTOM
                logic: |
                  .response.body.error == null
                  and .response.body.result[1].policy == "{{ .observed.composite.resource.spec.order }}"
                  and .response.body.result[1].startVlanId == {{ .observed.composite.resource.spec.range.start }}
                  and .response.body.result[1].endVlanId == {{ .observed.composite.resource.spec.range.end }}

              isRemovedCheck:
                type: CUSTOM
                logic: |
                  .response.body.error == null
                  and .response.body.result[1].policy == "ascending"
                  and .response.body.result[1].startVlanId == 1006
                  and .response.body.result[1].endVlanId == 4094


  - step: auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
