apiVersion: eos.netclab.dev/v1alpha1
kind: RoutedInterface
metadata:
  name: ceos01e1
spec:
  endpoint: ceos01.default.svc.cluster.local
  ifName: Ethernet1
  ipv4Address: 10.1.2.1
  ipv4PrefixLength: 24
