apiVersion: eos.netclab.dev/v1alpha1
kind: VlanInternalAllocation
metadata:
  name: ceos01
spec:
  target: http://ceos01.default.svc.cluster.local:6021
  creds: YXJpc3RhOmFyaXN0YQ==
  order: ascending
  range:
    start: 1006
    end: 1199
