apiVersion: eos.netclab.dev/v1alpha1
kind: VlanInternalAllocation
metadata:
  name: ceos01
spec:
  endpoint: ceos01.default.svc.cluster.local
  order: ascending
  range:
    start: 1006
    end: 1199
