apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bgppeergroups.eos.netclab.dev
spec:
  compositeTypeRef:
    apiVersion: eos.netclab.dev/v1alpha1
    kind: BgpPeerGroup
  mode: Pipeline
  pipeline:
  - step: create-request
    functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          apiVersion: http.crossplane.io/v1alpha2
          kind: Request
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ .observed.composite.resource.metadata.name }}
          spec:
            forProvider:
              insecureSkipTLSVerify: true
              headers:
                Accept: ["application/yang-data+json"]
                Authorization: ["Basic {{ .observed.composite.resource.spec.creds }}"]
              payload:
                baseUrl: "{{ .observed.composite.resource.spec.deviceUrl }}/restconf/data/openconfig-network-instance:network-instances/network-instance=default/protocols/protocol=BGP,BGP/bgp/peer-groups/peer-group={{ .observed.composite.resource.spec.name }}"
                body: |
                  {
                    "openconfig-network-instance:config":
                      {
                        "peer-group-name": "{{ .observed.composite.resource.spec.name }}"

                        {{- if hasKey .observed.composite.resource.spec "nextHopUnchanged" }}
                        ,"arista-exp-eos-bgp:next-hop-unchanged": {{ .observed.composite.resource.spec.nextHopUnchanged }}
                        {{- else }}
                        ,"arista-exp-eos-bgp:next-hop-unchanged": false
                        {{- end }}

                        {{- if hasKey .observed.composite.resource.spec "sendCommunityTypes" }}
                        ,"send-community-type":
                          [
                          {{- range $i, $v := .observed.composite.resource.spec.sendCommunityTypes }}
                            {{- if $i }},{{ end }}"{{ $v }}"
                          {{- end }}
                          ]
                        {{- end }}

                      }
                  }

              mappings:
              - action: CREATE
                method: PATCH
                body: .payload.body
                url: .payload.baseUrl

              - action: UPDATE
                method: PATCH
                url: .payload.baseUrl
                body: .payload.body

              - action: OBSERVE
                url: .payload.baseUrl

              - action: REMOVE
                method: DELETE
                url: .payload.baseUrl
                body: .payload.body


  - step: auto-ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
