apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: loopbackinterfaces.eos.netclab.dev
spec:
  defaultCompositionRef:
    name: loopbackinterfaces.eos.netclab.dev
  scope: Cluster
  group: eos.netclab.dev
  names:
    kind: LoopbackInterface
    plural: loopbackinterfaces
    categories:
    - crossplane
    - netclab
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
      - name: ENDPOINT
        type: string
        jsonPath: .spec.endpoint
      - name: IF
        type: string
        jsonPath: .spec.ifName
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                endpoint:
                  type: string
                ifName:
                  type: string
              required:
                - endpoint
                - ifName
