apiVersion: eos.netclab.dev/v1alpha1
kind: Router
metadata:
  name: dc1-spine1
spec:
  endpoint: dc1-spine1.default.svc.cluster.local

  bgp:
    asn: 65100
    routerId: 10.255.0.1
    bgpDefaultIpv4Unicast: false

    maximumPaths:
      ecmp: 4
      ecmpInstalled: 4

    redistribute:
      connected:
        route-map: RM-CONN-2-BGP

    bgpPeerGroups:
    - peerGroupName: EVPN-OVERLAY-PEERS
      nextHopUnchanged: true
      updateSource: Loopback0
      bfd: true
      ebgpMultihop: 3
      maximumRoutes: 0
      sendCommunityTypes:
      - EXTENDED
      - STANDARD
      afi:
        evpn: true
        ipv4: false

    bgpNeighbors:
    - neighborAsn: 65101
      neighborIp: 10.255.0.3
      peerGroup: EVPN-OVERLAY-PEERS



  #################
  spanningTree:
    mode: none

  #################
  bfd:
    multihop:
      interval: 300
      minRx: 300
      multiplier: 3

  #################
  routedInterfaces:
  - ifName: Ethernet1
    ipv4Address: 10.255.255.0
    ipv4PrefixLength: 31
