apiVersion: eos.netclab.dev/v1alpha1
kind: Router
metadata:
  name: ceos01
spec:
  nodePort: ceos01.default.svc.cluster.local:6020
  creds: YXJpc3RhOmFyaXN0YQ==
  asn: 65001
  routerId: 10.0.0.1

  ipVirtualRouter:
    macAddress: 00:1c:73:00:00:99

  virtualIpAddress:
    - sourceNat:
        vrf: VRF10
        address: 10.255.10.3
    - sourceNat:
        vrf: VRF11
        address: 10.255.11.3

  vlanInternal:
    order: ascending
    range:
      start: 1006
      end: 1199

  spanningTree:
    mode: mstp
    noSpanningTreeVlans: 4093-4094
    priority:
    - mst: 0
      priority: 4096

  vlans:
  - vlan: 11
    name: VRF10_VLAN11
  - vlan: 12
    name: VRF10_VLAN12
  - vlan: 21
    name: VRF11_VLAN21
  - vlan: 22
    name: VRF11_VLAN22
  - vlan: 3009
    name: MLAG_L3_VRF_VRF10
    trunkGroup: MLAG
  - vlan: 3010
    name: MLAG_L3_VRF_VRF11
    trunkGroup: MLAG
  - vlan: 3401
    name: L2_VLAN3401
  - vlan: 3402
    name: L2_VLAN3402
  - vlan: 4093
    name: MLAG_L3
    trunkGroup: MLAG
  - vlan: 4094
    name: MLAG
    trunkGroup: MLAG

  vrfs:
  - name: VRF10
  - name: VRF11

  ###################
  switchedInterfaces:
  - name: Port-Channel3
    description: MLAG_dc1-leaf1b_Port-Channel3
    shutdown: no
    switchportMode: trunk
    switchportTrunkGroup: MLAG

  - name: Port-Channel5
    description: SERVER_dc1-leaf1-server1_Bond1
    shutdown: no
    switchportTrunkNativeVlan: 4092
    switchportTrunkAllowedVlan: 11-12,21-22
    switchportMode: trunk
    mlag: 5
    spanningTree:
      portfast: edge

  - name: Port-Channel8
    description: L2_dc1-leaf1c_Port-Channel1
    shutdown: no
    switchportTrunkAllowedVlan: 11-12,21-22,3401-3402
    switchportMode: trunk
    mlag: 8

  ###################
  routedInterfaces:
  - name: Ethernet1
    description: P2P_dc1-spine1_Ethernet1
    mtu: 1500
    ipv4Address: 10.255.255.1
    ipv4PrefixLength: 31
    vrf: default
    shutdown: no

  - name: Loopback0
    description: ROUTER_ID
    shutdown: no
    ipv4Address: 10.255.0.3
    ipv4PrefixLength: 32
    vrf: default

  - name: Loopback1
    description: VXLAN_TUNNEL_SOURCE
    shutdown: no
    ipv4Address: 10.255.1.3
    ipv4PrefixLength: 32
    vrf: default

  - name: Loopback10
    description: DIAG_VRF_VRF10
    ipv4Address: 10.255.10.3
    ipv4PrefixLength: 32
    vrf: VRF10
    shutdown: no

  - name: Loopback11
    description: DIAG_VRF_VRF11
    ipv4Address: 10.255.11.3
    ipv4PrefixLength: 32
    vrf: VRF11
    shutdown: no

  - name: Vlan11
    description: VRF10_VLAN11
    mtu: 1500
    vrf: VRF10
    virtualIp: yes
    ipv4Address: 10.10.11.1
    ipv4PrefixLength: 24
    shutdown: no

  - name: Vlan12
    description: VRF10_VLAN12
    mtu: 1500
    shutdown: no
    vrf: VRF10
    virtualIp: yes
    ipv4Address: 10.10.12.1
    ipv4PrefixLength: 24

  - name: Vlan3009
    description: MLAG_L3_VRF_VRF10
    shutdown: no
    mtu: 1500
    vrf: VRF10
    ipv4Address: 10.255.1.96
    ipv4PrefixLength: 31

  - name: Vlan4094
    description: MLAG
    shutdown: no
    mtu: 1500
    ipv4Address: 10.255.1.64
    ipv4PrefixLength: 31
    autostate: no

  ###################
  vxlanInterfaces:
  - name: Vxlan1
    vxlanSourceInterface: Loopback1
    vxlanVirtualRouterEncapsulationMacAddress: mlag-system-id
    vxlanUdpPort: 4789
    vxlanVlanMap:
    - "11": 10011
    - "12": 10012
    - "21": 10021
    - "22": 10022
    - "3401": 13401
    - "3402": 13402
    vxlanVrfMap:
    - "VRF10": 10
    - "VRF11": 11

  bgpNeighbors:
  - networkInstance: default
    neighborAsn: 65002
    neighborIp: 10.1.2.2
