apiVersion: eos.netclab.dev/v1alpha1
kind: BgpPeerGroup
metadata:
  name: evpn-overlay-peers
spec:
  device: ceos01.default.svc.cluster.local
  creds: YXJpc3RhOmFyaXN0YQ==
  peerGroupName: EVPN-OVERLAY-PEERS
  nextHopUnchanged: true
  updateSource: Loopback0
  bfd: true
  ebgpMultihop: 3
  maximumRoutes: 0
  sendCommunityTypes:
  - EXTENDED
  - STANDARD
