apiVersion: eos.netclab.dev/v1alpha1
kind: BgpGlobal
metadata:
  name: ceos01
spec:
  deviceUrl: https://ceos01.default.svc.cluster.local:6020
  creds: YXJpc3RhOmFyaXN0YQ==
  asn: 65001
  routerId: 10.0.0.1
