apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: eosrouters.eos.netclab.dev
spec:
  scope: Cluster
  group: eos.netclab.dev
  names:
    kind: EosRouter
    plural: eosrouters
    categories:
      - crossplane
      - netclab

  versions:
    - name: v1alpha1
      served: true
      referenceable: true

      additionalPrinterColumns:
        - name: NODE-PORT
          type: string
          jsonPath: .spec.nodePort
        - name: ASN
          type: integer
          jsonPath: .spec.asn
        - name: ROUTER-ID
          type: string
          jsonPath: .spec.routerId
        - name: INTERFACES
          type: integer
          jsonPath: .spec.routedInterfaces | length(@)
        - name: BGP-NEIGHBORS
          type: integer
          jsonPath: .spec.bgpNeighbors | length(@)

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:

                nodePort:
                  type: string

                creds:
                  type: string
                  description: >-
                    Base64-encoded username:password string

                asn:
                  type: integer

                routerId:
                  type: string

                routedInterfaces:
                  type: array
                  description: Routed L3 interfaces
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ipv4Address:
                        type: string
                      ipv4Prefix:
                        type: integer
                    required:
                      - name
                      - ipv4Address
                      - ipv4Prefix

                bgpNeighbors:
                  type: array
                  description: BGP neighbors configuration
                  items:
                    type: object
                    properties:
                      networkInstance:
                        type: string
                      neighborAsn:
                        type: integer
                      neighborIp:
                        type: string
                    required:
                      - networkInstance
                      - neighborAsn
                      - neighborIp

              required:
                - nodePort
                - creds
                - asn
                - routerId
