apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: routers.eos.netclab.dev
spec:
  scope: Cluster
  group: eos.netclab.dev
  names:
    kind: Router
    plural: routers
    categories:
    - crossplane
    - netclab

  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    additionalPrinterColumns:
    - name: ENDPOINT
      type: string
      jsonPath: .spec.endpoint
    - name: ASN
      type: integer
      jsonPath: .spec.asn
    - name: ROUTER-ID
      type: string
      jsonPath: .spec.routerId

    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              endpoint:
                type: string
              asn:
                type: integer
              routerId:
                type: string
              routedInterfaces:
                type: array
                items:
                  type: object
                  properties:
                    ifName:
                      type: string
                    ipv4Address:
                      type: string
                    ipv4PrefixLength:
                      type: integer
                  required:
                  - ifName
                  - ipv4Address
                  - ipv4PrefixLength
              bgpNeighbors:
                type: array
                items:
                  type: object
                  properties:
                    networkInstance:
                      type: string
                      default: default
                    neighborAsn:
                      type: integer
                    neighborIp:
                      type: string
                  required:
                  - neighborAsn
                  - neighborIp
            required:
            - endpoint
            - asn
            - routerId
