apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: bgpglobals.eos.netclab.dev
spec:
  scope: Cluster
  group: eos.netclab.dev
  names:
    kind: BgpGlobal
    plural: bgpglobals
    categories:
    - crossplane
    - netclab
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
      - name: DEVICE-URL
        type: string
        jsonPath: .spec.deviceUrl
      - name: ASN
        type: integer
        jsonPath: .spec.asn
      - name: ROUTER-ID
        type: string
        jsonPath: .spec.routerId
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deviceUrl:
                  type: string
                creds:
                  type: string
                asn:
                  type: integer
                routerId:
                  type: string
              required:
                - deviceUrl
                - creds
                - asn
                - routerId
